// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProxy(arg1:main.ProxyConfig):Promise<string>;

export function DeleteProxy(arg1:string):Promise<void>;

export function ExportConfig():Promise<string>;

export function ExportConfigToFile():Promise<void>;

export function GetAllProxies():Promise<Array<main.ProxyWithStatus>>;

export function GetProxyStatus(arg1:string):Promise<main.ProxyStatus>;

export function GetStats():Promise<Record<string, number>>;

export function ImportConfig(arg1:string):Promise<void>;

export function ImportConfigFromFile():Promise<void>;

export function StartAllProxies():Promise<Array<string>>;

export function StartProxy(arg1:string):Promise<void>;

export function StopAllProxies():Promise<Array<string>>;

export function StopProxy(arg1:string):Promise<void>;

export function UpdateProxy(arg1:main.ProxyConfig):Promise<void>;
