// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1) {
  return window['go']['main']['App']['AddProxy'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportConfigToFile() {
  return window['go']['main']['App']['ExportConfigToFile']();
}

export function GetAllProxies() {
  return window['go']['main']['App']['GetAllProxies']();
}

export function GetProxyStatus(arg1) {
  return window['go']['main']['App']['GetProxyStatus'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ImportConfigFromFile() {
  return window['go']['main']['App']['ImportConfigFromFile']();
}

export function StartAllProxies() {
  return window['go']['main']['App']['StartAllProxies']();
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopAllProxies() {
  return window['go']['main']['App']['StopAllProxies']();
}

export function StopProxy(arg1) {
  return window['go']['main']['App']['StopProxy'](arg1);
}

export function UpdateProxy(arg1) {
  return window['go']['main']['App']['UpdateProxy'](arg1);
}
