name: Build Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: windows/amd64
            output: proxy-manager-desktop.exe
          - os: macos-latest
            platform: darwin/amd64
            output: proxy-manager-desktop.app

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install Go dependencies
      run: go mod download

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Fix vite permissions (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x frontend/node_modules/.bin/vite
        chmod +x frontend/node_modules/.bin/*

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Build application
      run: wails build -platform ${{ matrix.platform }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: build/bin/

    - name: List build files (debug)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Build directory contents:"
        ls -la build/bin/ || echo "build/bin/ does not exist"
        find build/ -type f -name "*" || echo "No files found in build/"

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/bin/*
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 