name: Build Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            artifact-name: proxy-manager-desktop-windows.exe
            build-name: windows
          - os: macos-latest
            platform: darwin/amd64
            artifact-name: proxy-manager-desktop-macos.zip
            build-name: macos

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install Go dependencies
      run: go mod download

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Fix permissions (Unix only)
      if: runner.os != 'Windows'
      run: chmod -R +x frontend/node_modules/.bin/

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Build application
      run: wails build -platform ${{ matrix.platform }} -clean

    - name: Prepare Windows release
      if: matrix.build-name == 'windows'
      run: |
        mkdir release
        copy "build\bin\proxy-manager-desktop.exe" "release\${{ matrix.artifact-name }}"

    - name: Prepare macOS release
      if: matrix.build-name == 'macos'
      run: |
        mkdir release
        cd build/bin
        zip -r ../../release/${{ matrix.artifact-name }} proxy-manager-desktop.app

    - name: Upload artifacts (always)
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.build-name }}
        path: release/${{ matrix.artifact-name }}
        if-no-files-found: error

    - name: Upload to release (only on release event)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: release/${{ matrix.artifact-name }}
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 